name: Prepare plugin as add-on

env:
  origin_branch: main
  target_branch: download

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  plugin-as-addon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.target_branch }}
      - run:
          echo "Configuring git"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          echo "Fetching from remote"
          git fetch

          echo "Pulling branch ${{ env.origin_branch }}"
          git pull origin ${{ env.origin_branch }}
          
          echo "Merging with ${{ env.origin_branch }}"
          git merge ${{ env.origin_branch }} -m "merging branch origin/${{ env.origin_branch }}" --allow-unrelated-histories

          echo "Removing unnecessary files"
          git rm --cached $(git ls-files -i --exclude-standard -c)
          git commit -m "removing unnecessary files"
          git push origin ${{ env.target_branch }}
